version:
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/node:8.10
        environment:
          TZ: "Asia/Jerusalem"
    steps:
      - checkout # special step to check out source code to working directory
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm-wee
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
      - run:
          name: eslint
          command: npm run lint
      - run:
          name: code-coverage
          command: npm test --coverage
      - store_artifacts:
          path: coverage
          prefix: coverage
